### ISSUE TITLE
It takes too long to save a gameobject

### ISSUE THREAD

**Issue by peterchen2001** [BayatGames/SaveGamePro#1]
Hi, I am using unity with version 2017.4.11f. I find that it takes me about 36 seconds to save one of my gameobjects with disk space size 19MB. Is this as expected? 

BTW, my gameobject has Mesh Render, Mesh Collider,Highlighter,Highlighter spectrum and mouse clock components.

**Comment by hasanbayatme** [comment]
Hi.
Maybe your GameObject is complex and have children with extra components, then that makes sense to take long to save and have such big disk size.
So, in this case, that's what we suggest to use Data models and structures.

Thanks.

**Comment by peterchen2001** [comment]
Hi,

Suppose that the gameobject A has its structure like below: A has a child gameobject B, and B has a child gameobject C.
A
--B
----C
Could you give me some code snippets on how to save and load gameobject A after there are some changes to A/B/C's components like transforms,materials and so on?

I need to find a way to quick save and load any gameobject in my scene using your APIs, how?

**Comment by hasanbayatme** [comment]
You can have a Data structure like this:
```csharp
public class MyData {
    public string name;
    // You can have your prefab name or resource path here and then instantiate the prefab when loading the data
    //public string prefabName;
    public Color materialColor;
    public Vector3 position;
    public MyData subData;
}
```
Here is how to save **A**:
```csharp
GameObject a = this.gameObject;
MyData data = new MyData();
data.name = a.name;
data.prefabName = "Prefabs/A";
data.materialColor = a.GetComponent<Renderer>().material.color;
// ... Assign other properties of MyData
// Add the subdata
MyData subData = new MyData();
subData.name = b.name;
subData.prefabName = "Prefabs/B";
// Then save the data
SaveGame.Save("game.dat", data);
```
And here is how to load it:
```csharp
MyData data = SaveGame.Load<MyData>("game.dat");
GameObject current = null;
while (data.subData != null) {
    GameObject prefab = Resources.Load<GameObject>(data.prefabName);
    current = Instantiate<GameObject>(prefab, data.position, Quaternion.identity);
    current.GetComponent<Renderer>().material.color = data,materialColor;
    // And assign other properties ...
    data = data.subData;
}
```
Hope you get what I mean, thanks!

**Comment by peterchen2001** [comment]
Thanks for your quick response.

Is it must to create prefab for each gameobject?

**Comment by hasanbayatme** [comment]
> Is it must create a prefab for each GameObject?

Yes, but not for all GameObjects that share the same components and details.

Thanks.

**Comment by peterchen2001** [comment]
It works to save my gameobject with multi-level children using the below test serializable class:
public class GameObjectEntry
{
    public string Name;
    public string PrefabName;
    public Color MaterialColor;
    public Vector3 Position;
    //public Material Material;
    public IList<GameObjectEntry> Children;
}
it runs very quick and the save space on disk is about 80k.

however, when i try to load it, it says below errors, any ideas?
ArgumentException: Arg_InsufficientSpace
Parameter name: chars
System.Text.UTF8Encoding.InternalGetChars (System.Byte* bytes, Int32 byteCount, System.Char* chars, Int32 charCount, System.UInt32& leftOverBits, System.UInt32& leftOverCount, System.Object provider, System.Text.DecoderFallbackBuffer& fallbackBuffer, System.Byte[]& bufferArg, Boolean flush) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Text/UTF8Encoding.cs:797)
System.Text.UTF8Encoding.InternalGetChars (System.Byte[] bytes, Int32 byteIndex, Int32 byteCount, System.Char[] chars, Int32 charIndex, System.UInt32& leftOverBits, System.UInt32& leftOverCount, System.Object provider, System.Text.DecoderFallbackBuffer& fallbackBuffer, System.Byte[]& bufferArg, Boolean flush) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Text/UTF8Encoding.cs:744)
System.Text.UTF8Encoding+UTF8Decoder.GetChars (System.Byte[] bytes, Int32 byteIndex, Int32 byteCount, System.Char[] chars, Int32 charIndex) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Text/UTF8Encoding.cs:1114)
System.IO.BinaryReader.ReadString () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/BinaryReader.cs:488)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectReader.ReadSavableMembers (System.Object obj, System.Type type) (at Assets/Plugins/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectReader.cs:881)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectReader.ReadObject (System.Type type, System.Object result) (at Assets/Plugins/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectReader.cs:849)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectReader.ReadObject (System.Type type) (at Assets/Plugins/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectReader.cs:807)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectReader.Read (System.Type type) (at Assets/Plugins/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectReader.cs:428)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectReader.ReadSavableMembers (System.Object obj, System.Type type) (at Assets/Plugins/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectReader.cs:868)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectReader.ReadObject (System.Type type, System.Object result) (at Assets/Plugins/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectReader.cs:849)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectReader.ReadObject (System.Type type) (at Assets/Plugins/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectReader.cs:807)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryObjectReader.Read (System.Type type) (at Assets/Plugins/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryObjectReader.cs:428)
BayatGames.SaveGamePro.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream input, System.Type type, SaveGameSettings settings) (at Assets/Plugins/BayatGames/SaveGamePro/Scripts/Serialization/Formatters/Binary/BinaryFormatter.cs:182)
BayatGames.SaveGamePro.SaveGame.Load (System.String identifier, System.Type type, System.Object defaultValue, SaveGameSettings settings) (at Assets/Plugins/BayatGames/SaveGamePro/Scripts/SaveGame.cs:349)
BayatGames.SaveGamePro.SaveGame.Load[GameObjectEntry] (System.String identifier) (at Assets/Plugins/BayatGames/SaveGamePro/Scripts/SaveGame.cs:259)
BayatGames.SaveGamePro.APIs.LoadGameAgent.LoadGameObject (System.String gameObjectFileName) (at Assets/Plugins/BayatGames/SaveGamePro/APIs/LoadGameAgent.cs:11)
UIController.SaveScene () (at Assets/Script/UI/UIController.cs:405)
UnityEngine.Events.InvokableCall.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:165)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:58)
UnityEngine.UI.Button.Press () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:36)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:45)
UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261)

**Comment by hasanbayatme** [comment]
Hi, I think you have a big amount of data, so can you tell how many GameObject you are saving?
Thanks.

**Comment by hasanbayatme** [comment]
Also, please update your review at Asset Store, thanks!

**Comment by hasanbayatme** [comment]
Closed, due to inactivity by OP
