### ISSUE TITLE
How to avoid the new instance by execution of SaveGame.Load<GameObjectEntry> () ?

### ISSUE THREAD

**Issue by peterchen2001** [BayatGames/SaveGamePro#2]
After testing, I found that execution of SaveGame.Load<GameObjectEntry>(identifier) new a gameobject each time. How to avoid this as I want to instantiate by GameObject.Instantiate<GameObject>(prefab, data.Position, Quaternion.identity)?

public class GameObjectEntry
{
    public string Name;
    // You can have your prefab name or resource path here and then instantiate the prefab when loading the data
    public string PrefabName;
    public Vector3 Position;
    public Material Material;
    public Light Light;
    public Transform Transform;
    public MeshFilter MeshFilter;
    public Image Image;
    public IList<GameObjectEntry> Children;
    public bool Saved;//标记是否已存盘
}

**Comment by hasanbayatme** [comment]
It is because you are saving Component subclasses, such as Transform and MeshFilter, you need to remove those fields and instead use their Raw data.
That's all, Thanks.

**Comment by hasanbayatme** [comment]
Closed, due to inactivity by OP
